name: Docker Deploy

on:
  push:
    branches:
      - main # Trigger this workflow on pushes to the `main` branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Store Docker Hub username in GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }} # Store Docker Hub password in GitHub Secrets

      - name: Build Docker image
        run: |
          docker build -t your-username/your-repository-name:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push your-username/your-repository-name:latest
